In [17]:
import pandas as pd
import numpy as np
import pickle
from stats_pipeline import helper_functions

In [11]:
with open('predictions/predictions.pickle', 'rb') as handle:
    predictions = pickle.load(handle)

In [21]:
predictions.keys()

dict_keys(['China', 'Macau', 'Taiwan', 'US', 'Japan', 'Thailand', 'South Korea', 'Hong Kong', 'Singapore', 'Vietnam', 'France', 'Australia', 'Nepal', 'Malaysia', 'Canada', 'Cambodia', 'Sri Lanka', 'Ivory Coast', 'Germany', 'Finland', 'United Arab Emirates', 'Philippines', 'India', 'Italy', 'UK', 'Russia', 'Sweden', 'Spain', 'Belgium', 'Others', 'Egypt', 'Iran', 'Israel', 'Lebanon', 'Oman', 'Afghanistan', 'Bahrain', 'Iraq', 'Kuwait', 'Austria', 'Algeria', 'Croatia', 'Switzerland', 'Pakistan', 'Brazil', 'Georgia', 'Greece', 'North Macedonia', 'Norway', 'Romania', 'Denmark', 'Estonia', 'Netherlands', 'San Marino', 'Belarus', 'Iceland', 'Lithuania', 'Mexico', 'New Zealand', 'Nigeria', 'Ireland', 'Luxembourg', 'Monaco', 'Qatar', 'Ecuador', 'Azerbaijan', 'Czech Republic', 'Armenia', 'Dominican Republic', 'Indonesia', 'Portugal', 'Andorra', 'Latvia', 'Morocco', 'Saudi Arabia', 'Senegal', 'Argentina', 'Chile', 'Jordan', 'Ukraine', 'Saint Barthelemy', 'Hungary', 'Faroe Islands', 'Gibraltar', 'Liechtenstein', 'Poland', 'Tunisia', 'Palestine', 'Bosnia and Herzegovina', 'Slovenia', 'South Africa', 'Bhutan', 'Cameroon', 'Colombia', 'Costa Rica', 'Peru', 'Serbia', 'Slovakia', 'Togo', 'Vatican City', 'French Guiana', 'Malta', 'Martinique', 'Bulgaria', 'Maldives', 'Bangladesh', 'Moldova', 'Paraguay', 'Albania', 'Cyprus', 'Brunei', 'Burkina Faso', 'Holy See', 'Mongolia', 'Panama', 'Bolivia', 'Honduras', 'Congo (Kinshasa)', 'Jamaica', 'Reunion', 'Turkey', 'Cuba', 'Guyana', 'Kazakhstan', 'Cayman Islands', 'Guadeloupe', 'Ethiopia', 'Sudan', 'Guinea', 'Antigua and Barbuda', 'Aruba', 'Kenya', 'Uruguay', 'Ghana', 'Jersey', 'Namibia', 'Seychelles', 'Trinidad and Tobago', 'Venezuela', 'Eswatini', 'Gabon', 'Guatemala', 'Guernsey', 'Mauritania', 'Rwanda', 'Saint Lucia', 'Saint Vincent and the Grenadines', 'Suriname', 'Kosovo', 'Central African Republic', 'Congo (Brazzaville)', 'Equatorial Guinea', 'Uzbekistan', 'Benin', 'Greenland', 'Liberia', 'Mayotte', 'Somalia', 'Tanzania', 'The Bahamas', 'Barbados', 'Montenegro', 'Kyrgyzstan', 'Mauritius', 'Zambia', 'Djibouti', 'Gambia, The', 'Bahamas, The', 'Chad', 'El Salvador', 'Fiji', 'Nicaragua', 'Madagascar', 'Haiti', 'Angola', 'Cabo Verde', 'Niger', 'Papua New Guinea', 'Zimbabwe', 'Eritrea', 'Uganda', 'Bahamas', 'Dominica', 'Gambia', 'Grenada', 'Mozambique', 'Syria', 'Timor-Leste', 'Belize', 'Laos', 'Libya', 'Diamond Princess', 'Guinea-Bissau', 'Mali', 'Saint Kitts and Nevis', 'West Bank and Gaza', 'Burma', 'MS Zaandam', 'Botswana', 'Burundi', 'Sierra Leone', 'Malawi', 'South Sudan', 'Western Sahara', 'Sao Tome and Principe', 'Yemen', 'Comoros', 'Tajikistan', 'Lesotho', 'total_stats'])

In [27]:
predictions["US"]["California"]

{'lower_test': [71729.49722502423,
  73537.21163726509,
  75796.94072561376,
  77722.20228978158,
  79811.79712873789,
  81179.35954669818,
  82245.23467172247,
  84489.49735628162,
  86942.1766798337,
  89240.82506347902,
  91562.619600226,
  93856.96050773062,
  95221.82401188387,
  97553.48682816346,
  100670.5088470717,
  102488.23801786298,
  105378.46236607495,
  108089.58035056759],
 'upper_test': [73387.34208993767,
  75185.51155454041,
  77448.69497532755,
  79362.46352478371,
  81442.24303936919,
  82813.62079783941,
  83888.1305738435,
  86146.79300028097,
  88613.21170622137,
  90904.10158207166,
  93216.5563649016,
  95501.26354439194,
  96882.58272005065,
  99209.42779224274,
  102367.482061224,
  104178.62716564807,
  107077.40826615739,
  109785.0202576021],
 'error_test': ['[422.92737979]',
  '[420.49239942]',
  '[421.37362287]',
  '[418.44167748]',
  '[415.9377222]',
  '[416.91104123]',
  '[419.11379879]',
  '[422.78726984]',
  '[426.29227873]',
  '[424.31303119]',
  '[421.93039712]',
  '[419.47276828]',
  '[423.67072081]',
  '[422.44168187]',
  '[432.90928495]',
  '[431.22964532]',
  '[433.4125304]',
  '[432.51812799]'],
 'forecast_test': [array([72558.41965748]),
  array([74361.3615959]),
  array([76622.81785047]),
  array([78542.33290728]),
  array([80627.02008405]),
  array([81996.49017227]),
  array([83066.68262278]),
  array([85318.14517828]),
  array([87777.69419303]),
  array([90072.46332278]),
  array([92389.58798256]),
  array([94679.11202606]),
  array([96052.20336597]),
  array([98381.4573102]),
  array([101518.99545415]),
  array([103333.43259176]),
  array([106227.93531612]),
  array([108937.30030408])],
 'forecast_dates': [datetime.date(2020, 5, 31),
  datetime.date(2020, 6, 1),
  datetime.date(2020, 6, 2),
  datetime.date(2020, 6, 3),
  datetime.date(2020, 6, 4),
  datetime.date(2020, 6, 5),
  datetime.date(2020, 6, 6)],
 'forecast': [112563.3325119225,
  115453.0598244818,
  118365.35935281993,
  121209.98899407419,
  124033.61681215672,
  126874.76798540431,
  129692.38740346165],
 'lower': [111699.3166278569,
  114118.30936425098,
  116494.82001517291,
  118674.38095803536,
  120766.48300511195,
  122837.4653277431,
  124824.3141770628],
 'upper': [113427.34839598811,
  116787.81028471261,
  120235.89869046694,
  123745.59703011301,
  127300.75061920148,
  130912.07064306551,
  134560.4606298605],
 'state_total_confirmed': '109,895',
 'state_total_deaths': '4,144',
 'state_total_recover': '0',
 'total_confirmed': '1,770,870',
 'total_deaths': '103,799',
 'total_recover': '185',
 'fatality_ratio': '0.00234009',
 'recovery_prof_ratio': '0.00000000',
 'all_cases': [2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  144.0,
  177.0,
  221.0,
  282.0,
  340.0,
  426.0,
  557.0,
  698.0,
  751.0,
  952.0,
  1177.0,
  1364.0,
  1646.0,
  2108.0,
  2538.0,
  2998.0,
  3899.0,
  4657.0,
  5095.0,
  5852.0,
  7138.0,
  8210.0,
  9399.0,
  10773.0,
  12004.0,
  12837.0,
  15034.0,
  16019.0,
  17351.0,
  18897.0,
  19710.0,
  21081.0,
  21706.0,
  22795.0,
  23931.0,
  25356.0,
  26686.0,
  27677.0,
  29157.0,
  30491.0,
  31431.0,
  33686.0,
  35465.0,
  37344.0,
  39561.0,
  41355.0,
  42368.0,
  43558.0,
  44966.0,
  46164.0,
  48747.0,
  50130.0,
  52026.0,
  53347.0,
  54903.0,
  55884.0,
  58456.0,
  60616.0,
  62148.0,
  63779.0,
  66558.0,
  67600.0,
  69329.0,
  70978.0,
  72798.0,
  74871.0,
  76693.0,
  78725.0,
  80166.0,
  81457.0,
  83752.0,
  85997.0,
  88031.0,
  90252.0,
  92539.0,
  94020.0,
  96400.0,
  99387.0,
  101050.0,
  103813.0,
  106622.0,
  109895.0],
 'all_dates': [datetime.date(2020, 1, 26),
  datetime.date(2020, 1, 27),
  datetime.date(2020, 1, 28),
  datetime.date(2020, 1, 29),
  datetime.date(2020, 1, 30),
  datetime.date(2020, 1, 31),
  datetime.date(2020, 3, 10),
  datetime.date(2020, 3, 11),
  datetime.date(2020, 3, 12),
  datetime.date(2020, 3, 13),
  datetime.date(2020, 3, 14),
  datetime.date(2020, 3, 15),
  datetime.date(2020, 3, 16),
  datetime.date(2020, 3, 17),
  datetime.date(2020, 3, 18),
  datetime.date(2020, 3, 19),
  datetime.date(2020, 3, 20),
  datetime.date(2020, 3, 21),
  datetime.date(2020, 3, 22),
  datetime.date(2020, 3, 23),
  datetime.date(2020, 3, 24),
  datetime.date(2020, 3, 25),
  datetime.date(2020, 3, 26),
  datetime.date(2020, 3, 27),
  datetime.date(2020, 3, 28),
  datetime.date(2020, 3, 29),
  datetime.date(2020, 3, 30),
  datetime.date(2020, 3, 31),
  datetime.date(2020, 4, 1),
  datetime.date(2020, 4, 2),
  datetime.date(2020, 4, 3),
  datetime.date(2020, 4, 4),
  datetime.date(2020, 4, 5),
  datetime.date(2020, 4, 6),
  datetime.date(2020, 4, 7),
  datetime.date(2020, 4, 8),
  datetime.date(2020, 4, 9),
  datetime.date(2020, 4, 10),
  datetime.date(2020, 4, 11),
  datetime.date(2020, 4, 12),
  datetime.date(2020, 4, 13),
  datetime.date(2020, 4, 14),
  datetime.date(2020, 4, 15),
  datetime.date(2020, 4, 16),
  datetime.date(2020, 4, 17),
  datetime.date(2020, 4, 18),
  datetime.date(2020, 4, 19),
  datetime.date(2020, 4, 20),
  datetime.date(2020, 4, 21),
  datetime.date(2020, 4, 22),
  datetime.date(2020, 4, 23),
  datetime.date(2020, 4, 24),
  datetime.date(2020, 4, 25),
  datetime.date(2020, 4, 26),
  datetime.date(2020, 4, 27),
  datetime.date(2020, 4, 28),
  datetime.date(2020, 4, 29),
  datetime.date(2020, 4, 30),
  datetime.date(2020, 5, 1),
  datetime.date(2020, 5, 2),
  datetime.date(2020, 5, 3),
  datetime.date(2020, 5, 4),
  datetime.date(2020, 5, 5),
  datetime.date(2020, 5, 6),
  datetime.date(2020, 5, 7),
  datetime.date(2020, 5, 8),
  datetime.date(2020, 5, 9),
  datetime.date(2020, 5, 10),
  datetime.date(2020, 5, 11),
  datetime.date(2020, 5, 12),
  datetime.date(2020, 5, 13),
  datetime.date(2020, 5, 14),
  datetime.date(2020, 5, 15),
  datetime.date(2020, 5, 16),
  datetime.date(2020, 5, 17),
  datetime.date(2020, 5, 18),
  datetime.date(2020, 5, 19),
  datetime.date(2020, 5, 20),
  datetime.date(2020, 5, 21),
  datetime.date(2020, 5, 22),
  datetime.date(2020, 5, 23),
  datetime.date(2020, 5, 24),
  datetime.date(2020, 5, 25),
  datetime.date(2020, 5, 26),
  datetime.date(2020, 5, 27),
  datetime.date(2020, 5, 28),
  datetime.date(2020, 5, 29),
  datetime.date(2020, 5, 30)],
 'train_cases': [2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  144.0,
  177.0,
  221.0,
  282.0,
  340.0,
  426.0,
  557.0,
  698.0,
  751.0,
  952.0,
  1177.0,
  1364.0,
  1646.0,
  2108.0,
  2538.0,
  2998.0,
  3899.0,
  4657.0,
  5095.0,
  5852.0,
  7138.0,
  8210.0,
  9399.0,
  10773.0,
  12004.0,
  12837.0,
  15034.0,
  16019.0,
  17351.0,
  18897.0,
  19710.0,
  21081.0,
  21706.0,
  22795.0,
  23931.0,
  25356.0,
  26686.0,
  27677.0,
  29157.0,
  30491.0,
  31431.0,
  33686.0,
  35465.0,
  37344.0,
  39561.0,
  41355.0,
  42368.0,
  43558.0,
  44966.0,
  46164.0,
  48747.0,
  50130.0,
  52026.0,
  53347.0,
  54903.0,
  55884.0,
  58456.0,
  60616.0,
  62148.0,
  63779.0,
  66558.0,
  67600.0,
  69329.0,
  70978.0,
  72798.0,
  74871.0,
  76693.0,
  78725.0,
  80166.0,
  81457.0,
  83752.0,
  85997.0,
  88031.0,
  90252.0,
  92539.0,
  94020.0,
  96400.0,
  99387.0,
  101050.0,
  103813.0,
  106622.0,
  109895.0],
 'train_dates': [datetime.date(2020, 1, 26),
  datetime.date(2020, 1, 27),
  datetime.date(2020, 1, 28),
  datetime.date(2020, 1, 29),
  datetime.date(2020, 1, 30),
  datetime.date(2020, 1, 31),
  datetime.date(2020, 3, 10),
  datetime.date(2020, 3, 11),
  datetime.date(2020, 3, 12),
  datetime.date(2020, 3, 13),
  datetime.date(2020, 3, 14),
  datetime.date(2020, 3, 15),
  datetime.date(2020, 3, 16),
  datetime.date(2020, 3, 17),
  datetime.date(2020, 3, 18),
  datetime.date(2020, 3, 19),
  datetime.date(2020, 3, 20),
  datetime.date(2020, 3, 21),
  datetime.date(2020, 3, 22),
  datetime.date(2020, 3, 23),
  datetime.date(2020, 3, 24),
  datetime.date(2020, 3, 25),
  datetime.date(2020, 3, 26),
  datetime.date(2020, 3, 27),
  datetime.date(2020, 3, 28),
  datetime.date(2020, 3, 29),
  datetime.date(2020, 3, 30),
  datetime.date(2020, 3, 31),
  datetime.date(2020, 4, 1),
  datetime.date(2020, 4, 2),
  datetime.date(2020, 4, 3),
  datetime.date(2020, 4, 4),
  datetime.date(2020, 4, 5),
  datetime.date(2020, 4, 6),
  datetime.date(2020, 4, 7),
  datetime.date(2020, 4, 8),
  datetime.date(2020, 4, 9),
  datetime.date(2020, 4, 10),
  datetime.date(2020, 4, 11),
  datetime.date(2020, 4, 12),
  datetime.date(2020, 4, 13),
  datetime.date(2020, 4, 14),
  datetime.date(2020, 4, 15),
  datetime.date(2020, 4, 16),
  datetime.date(2020, 4, 17),
  datetime.date(2020, 4, 18),
  datetime.date(2020, 4, 19),
  datetime.date(2020, 4, 20),
  datetime.date(2020, 4, 21),
  datetime.date(2020, 4, 22),
  datetime.date(2020, 4, 23),
  datetime.date(2020, 4, 24),
  datetime.date(2020, 4, 25),
  datetime.date(2020, 4, 26),
  datetime.date(2020, 4, 27),
  datetime.date(2020, 4, 28),
  datetime.date(2020, 4, 29),
  datetime.date(2020, 4, 30),
  datetime.date(2020, 5, 1),
  datetime.date(2020, 5, 2),
  datetime.date(2020, 5, 3),
  datetime.date(2020, 5, 4),
  datetime.date(2020, 5, 5),
  datetime.date(2020, 5, 6),
  datetime.date(2020, 5, 7),
  datetime.date(2020, 5, 8),
  datetime.date(2020, 5, 9),
  datetime.date(2020, 5, 10),
  datetime.date(2020, 5, 11),
  datetime.date(2020, 5, 12)],
 'test_dates': [datetime.date(2020, 5, 13),
  datetime.date(2020, 5, 14),
  datetime.date(2020, 5, 15),
  datetime.date(2020, 5, 16),
  datetime.date(2020, 5, 17),
  datetime.date(2020, 5, 18),
  datetime.date(2020, 5, 19),
  datetime.date(2020, 5, 20),
  datetime.date(2020, 5, 21),
  datetime.date(2020, 5, 22),
  datetime.date(2020, 5, 23),
  datetime.date(2020, 5, 24),
  datetime.date(2020, 5, 25),
  datetime.date(2020, 5, 26),
  datetime.date(2020, 5, 27),
  datetime.date(2020, 5, 28),
  datetime.date(2020, 5, 29),
  datetime.date(2020, 5, 30)],
 'test_cases': [72798.0,
  74871.0,
  76693.0,
  78725.0,
  80166.0,
  81457.0,
  83752.0,
  85997.0,
  88031.0,
  90252.0,
  92539.0,
  94020.0,
  96400.0,
  99387.0,
  101050.0,
  103813.0,
  106622.0,
  109895.0],
 'train_original': [2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  2.0,
  144.0,
  177.0,
  221.0,
  282.0,
  340.0,
  426.0,
  557.0,
  698.0,
  751.0,
  952.0,
  1177.0,
  1364.0,
  1646.0,
  2108.0,
  2538.0,
  2998.0,
  3899.0,
  4657.0,
  5095.0,
  5852.0,
  7138.0,
  8210.0,
  9399.0,
  10773.0,
  12004.0,
  12837.0,
  15034.0,
  16019.0,
  17351.0,
  18897.0,
  19710.0,
  21081.0,
  21706.0,
  22795.0,
  23931.0,
  25356.0,
  26686.0,
  27677.0,
  29157.0,
  30491.0,
  31431.0,
  33686.0,
  35465.0,
  37344.0,
  39561.0,
  41355.0,
  42368.0,
  43558.0,
  44966.0,
  46164.0,
  48747.0,
  50130.0,
  52026.0,
  53347.0,
  54903.0,
  55884.0,
  58456.0,
  60616.0,
  62148.0,
  63779.0,
  66558.0,
  67600.0,
  69329.0,
  70978.0]}

In [1]:
dataset.head()

NameError: name 'dataset' is not defined

In [18]:
dataset['Country/Region'] = dataset['Country/Region'].apply(lambda x:'China' if x=='Mainland China' else x)
dataset['Province/State'] = dataset['Province/State'].apply(lambda x:'Chicago' if x=='Chicago, IL' else x)
dataset['Province/State'].fillna("All", inplace=True)
dataset.loc[dataset['Province/State'] == 'Taiwan', 'Country/Region'] = "Taiwan"
dataset.loc[dataset['Province/State'] == 'Macau', 'Country/Region'] = "Macau"
indexNames = dataset[ (dataset['Confirmed'] == 0) & (dataset['Deaths'] == 0) & (dataset['Recovered'] == 0) ].index
dataset.drop(indexNames , inplace=True)
indexNames = dataset[(dataset['Confirmed'] == 0)].index
dataset.drop(indexNames, inplace=True)

dataset = helper_functions.convert_datetime(dataset)

In [19]:
dataset.head()

,SNo,Country/Region,Province/State,date,time,Last Update,Confirmed,Deaths,Recovered
0,1,China,Anhui,2020-01-22,00:00:00,1/22/2020 17:00,1.0,0.0,0.0
1,2,China,Beijing,2020-01-22,00:00:00,1/22/2020 17:00,14.0,0.0,0.0
2,3,China,Chongqing,2020-01-22,00:00:00,1/22/2020 17:00,6.0,0.0,0.0
3,4,China,Fujian,2020-01-22,00:00:00,1/22/2020 17:00,1.0,0.0,0.0
5,6,China,Guangdong,2020-01-22,00:00:00,1/22/2020 17:00,26.0,0.0,0.0

In [28]:
dataset[(dataset["Country/Region"]=="US") & (dataset["Province/State"]=="California")]

,SNo,Country/Region,Province/State,date,time,Last Update,Confirmed,Deaths,Recovered
204,205,US,California,2020-01-26,00:00:00,1/26/20 16:00,2.0,0.0,0.0
251,252,US,California,2020-01-27,00:00:00,1/27/20 23:59,2.0,0.0,0.0
302,303,US,California,2020-01-28,00:00:00,1/28/20 23:00,2.0,0.0,0.0
354,355,US,California,2020-01-29,00:00:00,1/29/20 19:30,2.0,0.0,0.0
409,410,US,California,2020-01-30,00:00:00,1/30/20 16:00,2.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...
33451,33452,US,California,2020-06-02,00:00:00,2020-06-03 02:33:13,117215.0,4305.0,0.0
34114,34115,US,California,2020-06-03,00:00:00,2020-06-04 02:33:14,119348.0,4374.0,0.0
34778,34779,US,California,2020-06-04,00:00:00,2020-06-05 02:33:06,122168.0,4444.0,0.0
35442,35443,US,California,2020-06-05,00:00:00,2020-06-06 02:33:00,125738.0,4529.0,0.0
36125,36126,US,California,2020-06-06,00:00:00,2020-06-07 03:53:30,128593.0,4606.0,0.0